# New ports collection makefile for: dpcrtlmm
# Date created:        1 April 2012
# Whom:                palmerv0r
#
# $FreeBSD$
#

PORTNAME=	dpcrtlmm
PORTVERSION=	1.2.0
CATEGORIES=	devel
MASTER_SITES=	http://downloads.daybologic.co.uk/ \
		https://bitbucket.org/daybologic/dpcrtlmm/get/

MAINTAINER=	palmer@overchat.org
COMMENT=	A memory manager and debugger for C programmers

#MAN1=		dpcrtlmm.1
MANCOMPRESSED=	yes
GNU_CONFIGURE=	yes

PLIST_FILES=	include/dpcrtlmm.h

.include <bsd.port.mk>
