# New ports collection makefile for: librttb
# Date created:        2 April 2012
# Whom:                palmerv0r
#
# $FreeBSD$
#

PORTNAME=	librttb
PORTVERSION=	0.0.4
CATEGORIES=	archivers
MASTER_SITES=	http://downloads.daybologic.co.uk/ \
		https://bitbucket.org/daybologic/rttb/get/

MAINTAINER=	palmer@overchat.org
COMMENT=	Run-Time TarBall library

#MAN1=		librttb.1
MANCOMPRESSED=	yes
GNU_CONFIGURE=	yes

PLIST_FILES=	include/rttb.h

.include <bsd.port.mk>
